/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ClientInfo {
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
}
