/**
 * Invoicer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateInvoiceProductItem } from './createInvoiceProductItem';


export interface CreateInvoiceCommand { 
    companyId?: string;
    clientId?: string;
    invoiceNumber: string;
    invoiceDate?: string;
    invoiceDue?: string;
    products: Array<CreateInvoiceProductItem>;
}

