/**
 * Invoicer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCompanyCommand { 
    name: string;
    address?: string | null;
    taxNumber?: string | null;
    phoneNumber?: string | null;
    email?: string | null;
    paymentDetails?: string | null;
    logoUrl?: string | null;
}

