/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateClientCommand {
  name: string;
  email: string;
  address?: string | null;
  taxNumber?: string | null;
  phoneNumber?: string | null;
  companyId?: string;
}
