/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type EstimateStatus = 0 | 1 | 2 | 3;

export const EstimateStatus = {
  NUMBER_0: 0 as EstimateStatus,
  NUMBER_1: 1 as EstimateStatus,
  NUMBER_2: 2 as EstimateStatus,
  NUMBER_3: 3 as EstimateStatus,
};
