/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceProductItem } from './invoiceProductItem';

export interface GetAllInvoicesResponse {
  id?: string;
  invoiceNumber?: string | null;
  invoiceDate?: string;
  invoiceDue?: string;
  clientId?: string;
  clientName?: string | null;
  products?: Array<InvoiceProductItem> | null;
}
