/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EstimateProductItem } from './estimateProductItem';
import { EstimateStatus } from './estimateStatus';

export interface GetAllEstimatesResponse {
  id?: string;
  estimateNumber?: string | null;
  estimateDate?: string;
  expiresOn?: string;
  status?: EstimateStatus;
  totalAmount?: number;
  subtotal?: number;
  taxAmount?: number;
  taxRate?: number;
  taxName?: string | null;
  notes?: string | null;
  clientId?: string;
  clientName?: string | null;
  products?: Array<EstimateProductItem> | null;
}
export namespace GetAllEstimatesResponse {}
