/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoicePaymentItem } from './invoicePaymentItem';
import { InvoiceStatus } from './invoiceStatus';
import { InvoiceProductItem } from './invoiceProductItem';

export interface GetAllInvoicesResponse {
  id?: string;
  invoiceNumber?: string | null;
  invoiceDate?: string;
  invoiceDue?: string;
  clientId?: string;
  clientName?: string | null;
  status?: InvoiceStatus;
  totalDue?: number;
  totalPaid?: number;
  products?: Array<InvoiceProductItem> | null;
  payments?: Array<InvoicePaymentItem> | null;
}
export namespace GetAllInvoicesResponse {}
