/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductInfo } from './productInfo';
import { ClientInfo } from './clientInfo';
import { CompanyInfo } from './companyInfo';

export interface GetPublicInvoiceResponse {
  id?: string;
  invoiceNumber?: string | null;
  invoiceDate?: string;
  dueDate?: string;
  status?: string | null;
  totalAmount?: number;
  notes?: string | null;
  company?: CompanyInfo;
  client?: ClientInfo;
  products?: Array<ProductInfo> | null;
}
