/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InvoiceProductItem {
  productId?: string;
  productName?: string | null;
  price?: number;
  quantity?: number;
}
