/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type InvoiceStatus = 0 | 1 | 2;

export const InvoiceStatus = {
  NUMBER_0: 0 as InvoiceStatus,
  NUMBER_1: 1 as InvoiceStatus,
  NUMBER_2: 2 as InvoiceStatus,
};
