/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const InvoiceStatus = {
  Unpaid: 'Unpaid',
  Partial: 'Partial',
  Paid: 'Paid',
} as const;
export type InvoiceStatus = (typeof InvoiceStatus)[keyof typeof InvoiceStatus];
