/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProductInfo {
  name?: string | null;
  quantity?: number;
  unitPrice?: number;
  totalPrice?: number;
}
