/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceStatus } from './invoiceStatus';

export interface RecordPaymentResponse {
  paymentId?: string;
  amount?: number;
  paidOn?: string;
  newInvoiceStatus?: InvoiceStatus;
}
export namespace RecordPaymentResponse {}
