/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateEstimateProductItem } from './updateEstimateProductItem';
import { EstimateStatus } from './estimateStatus';

export interface UpdateEstimateCommand {
  companyId?: string;
  estimateId?: string;
  clientId?: string | null;
  estimateDate?: string | null;
  expiresOn?: string | null;
  status?: EstimateStatus;
  notes?: string | null;
  products?: Array<UpdateEstimateProductItem> | null;
}
export namespace UpdateEstimateCommand {}
