/**
 * Invoicer API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateClientCommand {
  companyId: string;
  clientId: string;
  name?: string | null;
  email?: string | null;
  address?: string | null;
  taxNumber?: string | null;
  phoneNumber?: string | null;
}
