/**
 * Invoicer API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateInvoiceProductItem } from './updateInvoiceProductItem';


export interface UpdateInvoiceCommand { 
    companyId?: string;
    invoiceId?: string;
    invoiceNumber?: string | null;
    invoiceDate?: string | null;
    invoiceDue?: string | null;
    clientId?: string | null;
    products?: Array<UpdateInvoiceProductItem> | null;
}

